---
- name: Create monitoring directory
  file:
    path: /opt/monitoring
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copy Prometheus configuration
  copy:
    src: prometheus.yml
    dest: /opt/monitoring/prometheus.yml
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Copy monitoring docker-compose
  copy:
    src: "{{ playbook_dir }}/../../docker/monitoring/docker-compose.yml"
    dest: /opt/monitoring/docker-compose.yml
    owner: ubuntu
    group: ubuntu

- name: Start monitoring stack
  docker_compose:
    project_src: /opt/monitoring
    state: present
  register: output

- name: Wait for Prometheus to be ready
  wait_for:
    port: 9090
    host: 0.0.0.0
    delay: 5
    timeout: 60

- name: Wait for Grafana to be ready
  wait_for:
    port: 3000
    host: 0.0.0.0
    delay: 5
    timeout: 60
