global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['webapp-server:9100']

  - job_name: 'webapp'
    static_configs:
      - targets: ['webapp-server:3000']
    metrics_path: '/metrics'
